/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/XyILlZHWDBa
 */
import { CardHeader, CardContent, Card } from "@/components/ui/card"

export function Features() {
  return (
    <>
      <div className="flex justify-center items-center w-full gap-10">
        <Card className="w-48 h-48 border-2 rounded-xl flex flex-col justify-center">
          <CardHeader>
            <div className="flex items-center justify-center">
              <HelpingHandIcon className="w-16 h-16 text-gray-500" />
            </div>
          </CardHeader>
          <CardContent>
            <h2 className="text-center text-xl font-semibold text-gray-500">Undrop a player</h2>
          </CardContent>
        </Card>
      </div>
    </>
  )
}


function HelpingHandIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 15 5.12-5.12A3 3 0 0 1 10.24 9H13a2 2 0 1 1 0 4h-2.5m4-.68 4.17-4.89a1.88 1.88 0 0 1 2.92 2.36l-4.2 5.94A3 3 0 0 1 14.96 17H9.83a2 2 0 0 0-1.42.59L7 19" />
      <path d="m2 14 6 6" />
    </svg>
  )
}
